### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by achrafelkhnissi** [Hendrixer/fullstack-app-v2-app#15]
I got this error:

TypeError: Cannot read properties of undefined (reading 'name')
src/middleware.ts (30:26) @ get
```js
  28 | 
  29 | // get the jwt from the cookie
> 30 | const jwt = req.cookies.get(process.env.COOKIE_NAME);
     |                        ^
  31 | 
  32 | if (!jwt) {
  33 |   req.nextUrl.pathname = "/signin";
```

The exact steps i took:
1. Clone the repo
2. Run `npm install`
3. Run `npm run dev`
4. Server Error.

My system: MacOS 13.4.1 (c) (22F770820d)

**Comment by dtauer** [comment]
I responded to you in our Discord, but adding it here too just to you see it:

Rename `.env.sample` to be `.env`. The application is looking for that COOKIE_NAME environment variable in a `.env` file
