### ISSUE TITLE
Font error

### ISSUE THREAD

**Issue by dgwyer** [Hendrixer/fullstack-app-v2-app#2]
In the [class notes](https://fullstack-v2-instructions.vercel.app/lessons/routes-and-pages/root-layouts) there is a reference to a Google font (Inter). This is causing a build error for me when following along with building the project from scratch.

```
error - app\(auth)\layout.tsx
`@next/font` error:
Missing selected subsets for font `Inter`. Please specify subsets in the function call or in your `next.config.js`. Read more: https://nextjs.org/docs/messages/google-fonts-missing-subsets
```

But in the repo, I noticed all references to this have been removed, apart from in [tailwind.config.js](https://github.com/Hendrixer/fullstack-app-v2-app/blob/main/tailwind.config.js). Should we just remove references to the font?

**Comment by dtauer** [comment]
Thanks for reporting this. Let me take a look. He doesn't reference the font at throughout the course, although the font doesn't render properly for him. I didn't have an issue with it when I went through it so let me double check.

**Comment by dtauer** [comment]
Did you use `create-next-app` to generate the initial project? That should have included `@next/font` as a dependency.

**Comment by dtauer** [comment]
If you have finished the routes section, you can look at the [routes branch](https://github.com/Hendrixer/fullstack-app-v2-app/tree/routes) and compare the `package.json` file there with yours to make sure you have all the dependencies.

**Comment by dgwyer** [comment]
Strange. I do have that dependency installed but was still getting the error. Not a big issue really as I deleted any references to the 'Inter' font. Maybe just remove them from the class notes?

**Comment by dtauer** [comment]
Since I couldn't reproduce it, I'm going to leave it in the notes....for now. I tested it again (following the edited course videos) and it worked. I'm going to see if we get more errors reported before I remove it. We do recommend using Node 16.x.x or 18.x.x with this course.

**Comment by dgwyer** [comment]
Sure, no problem. I'll probably run through the course again sometime soon so will see if I have a similar problem next time. I'm using Node 16.x.x so hopefully that shouldn't be an issue as you mentioned.
