### ISSUE TITLE
Issue with Typescript

### ISSUE THREAD

**Issue by leofmoura** [Hendrixer/fullstack-app-v2-app#5]
All my tsx files are not recognizing Typescript.
I'm not sure what is missing, looks like a issue with new Nextjs project.
Any thoughts on that?

Thanks

<img width="730" alt="image" src="https://user-images.githubusercontent.com/3877117/228095611-06527bfb-e0f5-4304-bcb8-cb50c8f5ee89.png">

**Comment by leofmoura** [comment]
This builds and run quite will.
Also, I tried restarting my TS Server on vscode and it does not fix the issue.

**Comment by dtauer** [comment]
@leofmoura First, you may want to make sure your `tsconfig.json` file has the correct configuration. Also, double check you have the `typescript` module installed. You can compare your project with the [typescript branch](https://github.com/Hendrixer/fullstack-app-v2-app/tree/typescript) to make sure the configuration matches.

**Comment by leofmoura** [comment]
I did not found so, started using typescript branch as source was a quick solution. Thanks
