### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'call')

### ISSUE THREAD

**Issue by mdzialo00** [Hendrixer/fullstack-app-v2-app#8]
Hi, I'm in the middle of the course and I cloned the repo. I've done only `npm install`, after that `npm run dev` and I'm getting this error in the browser:
![image](https://user-images.githubusercontent.com/49043489/231758514-0c631ae6-71a7-4c1f-9d86-8bbe531fb4f8.png)

Node: 16.16.0
NPM: 8.11.0

**Comment by martisss** [comment]
I also hit this error, i try to checout to different branch, but it just doesn`t work.

**Comment by mdzialo00** [comment]
> I also hit this error, i try to checout to different branch, but it just doesn`t work.

I've also tried other branches, but any of them don't work for me.

**Comment by MiltonChung** [comment]
Could be something incompatible with the dependencies. I played around with it and changed the next version to 13.2 and seems to work. I just started the course so I'm not too sure if it'll run into other problems when following along

```
"dependencies": {
    "@next/font": "13.2.0",
    "@types/node": "18.15.12",
    "@types/react": "18.0.37",
    "@types/react-dom": "18.0.11",
    "eslint": "8.38.0",
    "eslint-config-next": "13.3.0",
    "next": "13.2.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "typescript": "4.9.4",
    "@prisma/client": "4.6.1",
    "bcrypt": "5.1.0",
    "class-variance-authority": "0.4.0",
    "clsx": "1.2.1",
    "cookie": "0.5.0",
    "css-reset-and-normalize": "2.3.6",
    "jose": "4.11.1",
    "react-feather": "2.0.10"
  },
  "devDependencies": {
    "prisma": "4.6.1",
    "tailwindcss": "3.2.4",
    "ts-node": "10.9.1",
    "tsconfig-paths": "4.1.1"
  }
```

**Comment by mdzialo00** [comment]
Upgrading next to `13.2.0` solves the issue for me 🎉
